ticketing_booking:
    path:     /booking
    defaults: { _controller: TicketingBundle:BookingProcess:booking }

ticketing_ckeckout:
    path:     /check-payment
    defaults: { _controller: TicketingBundle:BookingProcess:checkout }
    methods: [POST]

ticketing_payment:
    path:     /payment
    defaults: { _controller: TicketingBundle:BookingProcess:payment }

ticketing_summary:
    path:     /summary
    defaults: { _controller: TicketingBundle:BookingProcess:summary }

ticketing_soldTicketsNb:
    path: /sold-tickets
    defaults: { _controller: TicketingBundle:BookingProcess:soldTicketsNb }
    methods: [POST]
